name: Flutter Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        java-version: '17.x'
        distribution: 'temurin'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.9'
    - run: flutter pub get
    - run: flutter test
