on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '12.x'
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.8'
      - name: Get dependencies
        run: flutter pub get
      - name: Test project
        run: flutter test
      - name: Create APK
        run: flutter build apk --split-per-abi
      - name: Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          allowUpdates: true
          replacesArtifacts: true
          tag: dev-release-${{github.run_number}}
          token: ${{ secrets.CRMAP2022_01 }}
      - name: Build release project
        run: flutter build web
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./build/web

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.CRMAP2022_01 }}
          publish_dir: ./build
