on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.8.1'
      - name: Get dependencies
        run: flutter pub get
      - name: Test project
        run: flutter test
      - run: flutter build apk --split-per-abi
#      - name: Create a Release APK
#        uses: ncipollo/release-action@v1
      #        with:
      #          artifacts: "build/app/outputs/apk/release/*.apk"
      #          allowUpdates: true
      #          replacesArtifacts: true
      #          token: ${{ secrets.CRMAP_TOKEN }}
      - name: Build release project
        run: flutter build web
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./build/web

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.CRMAP_TOKEN }}
          publish_dir: ./build